name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Dotnet build

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test .NET 5.0
      run: dotnet test -f net5.0 --configuration Release --no-restore --no-build --verbosity normal
    - name: Test .NET Core 3.1
      run: dotnet test -f netcoreapp3.1 --configuration Release --no-restore --no-build --verbosity normal
